In [13]:
import pandas as pd
import numpy as np

In [27]:
data = pd.read_excel("DATA_moles.xlsx")

In [28]:
data

,Unnamed: 0,Experiment,DMF,H2O_vol,Acid_vol,Acid_pKa,ACID,Temperature,Time_h_calc,%FA_formed(w/w),SD,Acid_moles,Unnamed: 12,Unnamed: 13,Unnamed: 14
0,1,4_13,8,1.56,0.38,0.00,TFAA,60,3.0,0.099534,0.011640,0.004966,NaN,NaN,NaN
1,2,4_13,8,0.84,0.46,0.00,TFAA,150,6.0,0.100667,0.010739,0.006011,NaN,NaN,NaN
2,3,4_13,8,0.68,1.14,-6.30,HCl,100,9.0,0.340075,0.042111,0.013680,NaN,NaN,NaN
3,4,4_13,8,1.48,0.06,2.86,ClAA,100,24.0,0.030610,0.001769,0.001003,NaN,NaN,NaN
4,5,4_13,8,3.48,0.94,4.75,AA,100,24.0,0.103782,0.023473,0.016450,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
172,173,4_11,8,0.00,0.50,-6.30,HCl,120,72.0,0.318390,0.036930,0.006000,NaN,NaN,NaN
173,174,4_11,8,0.00,1.00,-6.30,HCl,120,72.0,0.673820,0.085490,0.012000,NaN,NaN,NaN
174,175,4_11,8,0.00,0.10,-6.30,HCl,120,168.0,0.065250,0.011350,0.001200,NaN,NaN,NaN
175,176,4_11,8,0.00,0.50,-6.30,HCl,120,168.0,0.365840,0.044320,0.006000,NaN,NaN,NaN
176,177,4_11,8,0.00,1.00,-6.30,HCl,120,168.0,0.495416,0.011728,0.012000,NaN,NaN,NaN

In [29]:
acids = data["ACID"].unique()

In [30]:
acids

array(['TFAA', 'HCl', 'ClAA', 'AA', 'DClAA', 'H2SO4', 'HNO3'],
      dtype=object)

In [31]:
def moles(ro, v, mr):
    return (ro*v)/mr

def moles_hcl(v):
    return 12*(v/1000)
def moles_hno3(v):
    return 15.8*(v/1000)

In [32]:
mr ={'TFAA':114.023,
    'AA':60,
    'DClAA':128.94,
    'H2SO4': 98.079 ,
    'HNO3':63,
    'ClAA':94.5}
ro ={'TFAA':1.49,
    'AA':1.05,
    'DClAA':1.5634,
    'H2SO4':1.83,
    'HNO3':1.51,
    'ClAA':1.58}

In [33]:
acid_moles = []

In [34]:
for index, row in data.iterrows():
    if row["ACID"] != 'HCl' and row["ACID"] != 'HNO3' and row["ACID"] != 'ClAA':
        if row["Acid_vol"] != 'nan':
            mls = moles(ro[row["ACID"]], row["Acid_vol"], mr[row["ACID"]])
            acid_moles.append(mls)
    elif row["ACID"] == 'HCl' :
        '''
        Because HCl is Aq. splution 
        '''
        mls = moles_hcl(row["Acid_vol"])
        acid_moles.append(mls)
        
    elif row["ACID"] == 'HNO3' :
        mls = moles_hno3(row["Acid_vol"])
        acid_moles.append(mls)
     
    elif row["ACID"] == 'ClAA' :
        acid_moles.append(row['Acid_moles'])

In [35]:
acid_moles

[0.004965664822009595,
 0.006011067942432655,
 0.01368,
 0.001003174603174603,
 0.01645,
 0.02184,
 0.01435,
 0.016732526756630988,
 0.02052427125072646,
 0.01541969602624032,
 0.023509619796286668,
 0.022435999999999998,
 0.010428,
 0.01365,
 0.008879999999999999,
 0.02905,
 0.02574814814814815,
 0.020399999999999998,
 0.011760785104759567,
 0.014792523654412904,
 0.005039999999999999,
 0.00455,
 0.0018658428409751326,
 0.0310984126984127,
 0.0003731685681950265,
 0.012852520552194819,
 0.019157530634403598,
 0.02708571428571429,
 0.013060899886825926,
 0.03545101397852751,
 0.00264,
 0.0021599999999999996,
 0.01156822561404582,
 0.025002294069066778,
 0.01960130850793261,
 0.030449999999999998,
 0.01576252520552195,
 0.008532,
 0.01785,
 0.007579172623067276,
 0.006533769502644203,
 0.01123808354454803,
 0.002340740740740741,
 0.003920261701586522,
 0.03619735111491757,
 0.01752,
 0.031284,
 0.02136,
 0.015484,
 0.004079999999999988,
 0.0316,
 0.024255956932676723,
 0.0315,
 0.02239011409170159,
 0.014374292905817248,
 0.01839153439153439,
 0.0024000000000000002,
 0.0316,
 0.006062509694431518,
 0.0012000000000000001,
 0.006687830687830689,
 0.006687830687830689,
 0.020399999999999998,
 0.024828324110047973,
 0.0024000000000000002,
 0.0072,
 0.011760785104759567,
 0.01225,
 0.01940003102218086,
 0.01679258556877619,
 0.012544837445076869,
 0.01123808354454803,
 0.0007317519999999998,
 0.051475153648068664,
 0.047068569,
 0.0037388140000000005,
 0.0021978650000000002,
 0.05148293974248927,
 0.015978290004238418,
 0.05139101665236051,
 0.038911881999999995,
 0.037269180999999985,
 0.05124810746781116,
 0.029791686000000005,
 0.004443434617350994,
 0.050471523090128756,
 0.049607274,
 0.04968998,
 0.049913858,
 0.04441139948497855,
 0.026858004,
 0.012939902,
 0.041225065922134325,
 0.05136,
 0.049915,
 0.034559999999999994,
 0.004582,
 0.03545101397852751,
 0.006790010857763301,
 0.01176,
 0.038759999999999996,
 0.03732,
 0.049875,
 0.015681046806346088,
 0.050050000000000004,
 0.0010454031204230726,
 0.009600000000000001,
 0.033114,
 0.0024828324110047974,
 0.04104,
 0.007457,
 0.05136,
 0.009975,
 0.02844,
 0.034071304482705136,
 0.03828,
 0.02555,
 0.02028,
 0.02355677150214592,
 0.026849334,
 0.03784954200000001,
 0.00977034025751073,
 0.04384988800000001,
 0.012723967725321889,
 0.04892067200000001,
 0.009304945236051503,
 0.005633647725321888,
 0.013397937999999995,
 0.008074455000000001,
 0.030795818000000003,
 0.036447700000000006,
 0.014905815,
 0.029911012,
 0.041269113,
 0.03949911244635193,
 0.011787823,
 0.01947072,
 0.027106886523605142,
 0.038615832,
 0.035,
 0.016269909012875533,
 0.017823825579399145,
 0.048621536,
 0.04947453733905578,
 0.01626661,
 0.03302470660944207,
 0.045350104377682394,
 0.0498692,
 0.039482549000000006,
 0.012733771673819734,
 0.02114257900000001,
 0.0064913980000000015,
 0.004079999999999988,
 0.0012000000000000001,
 0.006,
 0.012,
 0.0012000000000000001,
 0.006,
 0.012,
 0.0012000000000000001,
 0.006,
 0.012,
 0.0012000000000000001,
 0.006,
 0.012,
 0.0012000000000000001,
 0.006,
 0.012,
 0.0012000000000000001,
 0.006,
 0.012,
 0.0012000000000000001,
 0.006,
 0.012,
 0.0012000000000000001,
 0.006,
 0.012]

In [36]:
data["Acid_moles"] = acid_moles

In [37]:
data.to_excel("DATA_moles.xlsx")